//// Generated by spider on 2020-04-20 11:45:57.780939

import 'dart:io';

import 'package:covid19/res/asset_images.dart';
import 'package:test/test.dart';

void main() {
  test('asset_images assets test', () {
    expect(true, File(AssetImages.noInternet).existsSync());
    expect(true, File(AssetImages.mythBusters).existsSync());
    expect(true, File(AssetImages.virus).existsSync());
    expect(true, File(AssetImages.prevention).existsSync());
    expect(true, File(AssetImages.genericError).existsSync());
    expect(true, File(AssetImages.latestNumbers).existsSync());
    expect(true, File(AssetImages.symptoms).existsSync());
  });
}
