//// Generated by spider on 2020-04-16 20:24:50.642530

import 'dart:io';

import 'package:covid19/res/asset_animations.dart';
import 'package:test/test.dart';

void main() {
  test('asset_animations assets test', () {
    expect(true, File(AssetAnimations.splash).existsSync());
  });
}
