//// Generated by spider on 2020-04-22 08:14:41.214589

class AssetImages {
  static const String noInternet = 'assets/images/no-internet.png';
  static const String mythBusters = 'assets/images/myth-busters.png';
  static const String virus = 'assets/images/virus.png';
  static const String prevention = 'assets/images/prevention.png';
  static const String splash = 'assets/images/splash.jpg';
  static const String genericError = 'assets/images/generic-error.png';
  static const String latestNumbers = 'assets/images/latest-numbers.png';
  static const String symptoms = 'assets/images/symptoms.png';
}
