//// Generated by spider on 2020-04-29 12:03:12.033772

class AssetImages {
  static const String noInternet = 'assets/images/no-internet.png';
  static const String fact = 'assets/images/fact.png';
  static const String mythBusters = 'assets/images/myth-busters.png';
  static const String virus = 'assets/images/virus.png';
  static const String prevention = 'assets/images/prevention.png';
  static const String splash = 'assets/images/splash.jpg';
  static const String statistics = 'assets/images/statistics.png';
  static const String genericError = 'assets/images/generic-error.png';
  static const String faq = 'assets/images/faq.png';
  static const String myth = 'assets/images/myth.png';
  static const String symptoms = 'assets/images/symptoms.png';
}
